// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    public static final class SwerveConstants {
        public static final double percentSlow = 0.35;
        public static final double smoothingFactor = 0.5;
        // Closer to 1: Faster changes (less smoothing), Closer to 0: Slower changes (more smoothing).
    } 

    public static final class ElevatorConstants {

        public static final double stage2UpperLimit = 3.02;
        public static final double stage2LowerLimit = 0;
        public static final double stage2SensorLimit = 3.08;

        public static final double stage1UpperLimit = 5.17;
        public static final double stage1LowerLimit = 0.06;
        public static final double stage1SensorLimit = 0;

    }

    public static final class VisionConstants {
        public static final String limelightName = "limelight-front";
        public static final String limeLightName2 = "limelight-back";

        public static final Pose2d ReefTagOffset = new Pose2d(0, Units.inchesToMeters(17.25), new Rotation2d(Math.PI));
        // public static final Pose2d CoralStationTagOffset = new Pose2d(0, Units.inchesToMeters(25), new Rotation2d()); 
        public static final Pose2d CoralStationTagOffset = new Pose2d(0, Units.inchesToMeters(27), new Rotation2d());
    }

}